### ISSUE TITLE
Couldnt run graph matching on image dataset

### ISSUE THREAD

**Issue by tomeramit** [ZhenZhang19920330/KerGM_Code#2]
Hi,
I tried to launch graph matchind on image dataset, but I couldn't make it, it seems that in the make1, there are some missing paths (that exists in GraphMatching_SyntheticDataset, but dont know if they are the same) and also in the addPath there are paths that does not exist.

(I fail on run('./vlfeat-0.9.20/toolbox/vl_setup') as well)

I'm new to matlab, so maybe there are some things that I'm not familiar with
Thanks!

**Comment by tomeramit** [comment]
just had to install the vlfeat and it worked

**Comment by ZhenZhang19920330** [comment]
Hello,

Thanks for your interest in our work. The following are my comments.

  1.  If something wrong happens when running "make1.m", then try to run "make2.m" as a following step.
  2.  Thanks for pointing out that  "vlfeat" file is missing. I just added that file to the repository.  Please try to run "addpath.m" again.

________________________________

**Comment by tomeramit** [comment]
Thanks for the response!

My goal is to try to launch the KerGM on my own dataset (for example 2 graphs) if you can give me some guidance for what to look and what to change I will be very glad :)

**Comment by ZhenZhang19920330** [comment]
feel free to let me know if you need any help re the code.

在 2020年3月4日，上午6:17，tomeramit <notifications@github.com> 写道：

﻿

Thanks for the response!

My goal is to try to launch the KerGM on my own dataset (for example 2 graphs) if you can give me some guidance for what to look and what to change I will be very glad :)
